import type { Metadata } from "next";
import { Red_Rose, Aboreto } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navigation/Navbar";
import Footer from "@/components/navigation/Footer";

const redrose = Red_Rose({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-red-rose",
});

const aboreto = Aboreto({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-aboreto",
});

export const metadata: Metadata = {
  title: "GMALLI STORES",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${redrose.variable} ${aboreto.variable}  antialiased`}>
        <Navbar/>
        {children}
        <Footer/>
        </body>
    </html>
  );
}
