export type Product = {
  id: string;
  name: string;
  category: string;
  price: number;
  brand: string;
  rating: number;
  inStock: boolean;
  image: string;
  priceRange: "Low" | "Mid" | "Sale";
  tags: string[];
};

export const allProducts: Product[] = [
  // Fresh Produce
  {
    id: "fp-1",
    name: "Roma Tomatoes",
    category: "Fresh Produce",
    price: 2.99,
    brand: "FarmFresh",
    rating: 4.5,
    inStock: true,
    image: "/images/pepper.jpg",
    priceRange: "Low",
    tags: ["Vegetables", "Organic"],
  },
  {
    id: "fp-2",
    name: "Bell Peppers Mix",
    category: "Fresh Produce",
    price: 3.49,
    brand: "GreenGarden",
    rating: 4.2,
    inStock: true,
    image: "/images/pepper.jpg",
    priceRange: "Low",
    tags: ["Vegetables"],
  },
  {
    id: "fp-3",
    name: "Organic Spinach",
    category: "Fresh Produce",
    price: 4.99,
    brand: "NatureFarm",
    rating: 4.7,
    inStock: false,
    image: "/images/pepper.jpg",
    priceRange: "Mid",
    tags: ["Vegetables", "Organic"],
  },
  {
    id: "fp-4",
    name: "Mango Bundle",
    category: "Fresh Produce",
    price: 5.99,
    brand: "TropicalFresh",
    rating: 4.8,
    inStock: true,
    image: "/images/pepper.jpg",
    priceRange: "Mid",
    tags: ["Fruits", "Tropical"],
  },
  {
    id: "fp-5",
    name: "Sweet Corn (6 pack)",
    category: "Fresh Produce",
    price: 3.99,
    brand: "FarmFresh",
    rating: 4.3,
    inStock: true,
    image: "/images/pepper.jpg",
    priceRange: "Low",
    tags: ["Vegetables"],
  },
  {
    id: "fp-6",
    name: "Avocado Pack",
    category: "Fresh Produce",
    price: 6.49,
    brand: "GreenGarden",
    rating: 4.6,
    inStock: true,
    image: "/images/pepper.jpg",
    priceRange: "Mid",
    tags: ["Fruits", "Organic"],
  },

  // Frozen Produce
  {
    id: "frz-1",
    name: "Frozen Mixed Vegetables",
    category: "Frozen Produce",
    price: 3.99,
    brand: "FrostFarm",
    rating: 4.0,
    inStock: true,
    image: "/images/frozenfood.jpg",
    priceRange: "Low",
    tags: ["Vegetables", "Ready to Cook"],
  },
  {
    id: "frz-2",
    name: "Frozen Chicken Strips",
    category: "Frozen Produce",
    price: 8.99,
    brand: "ChillBite",
    rating: 4.4,
    inStock: true,
    image: "/images/frozenfood.jpg",
    priceRange: "Mid",
    tags: ["Protein", "Ready to Cook"],
  },
  {
    id: "frz-3",
    name: "Frozen Jollof Rice",
    category: "Frozen Produce",
    price: 6.49,
    brand: "AfroFrost",
    rating: 4.7,
    inStock: false,
    image: "/images/frozenfood.jpg",
    priceRange: "Mid",
    tags: ["Meals", "African"],
  },
  {
    id: "frz-4",
    name: "Frozen Plantain Slices",
    category: "Frozen Produce",
    price: 4.99,
    brand: "AfroFrost",
    rating: 4.9,
    inStock: true,
    image: "/images/frozenfood.jpg",
    priceRange: "Low",
    tags: ["Fruits", "African"],
  },

  // Eggs
  {
    id: "eg-1",
    name: "Free Range Eggs (12)",
    category: "Eggs",
    price: 4.99,
    brand: "HappyHen",
    rating: 4.8,
    inStock: true,
    image: "/images/eggs.jpg",
    priceRange: "Low",
    tags: ["Free Range", "Organic"],
  },
  {
    id: "eg-2",
    name: "Large White Eggs (30)",
    category: "Eggs",
    price: 7.99,
    brand: "FarmGate",
    rating: 4.3,
    inStock: true,
    image: "/images/eggs.jpg",
    priceRange: "Mid",
    tags: ["Bulk"],
  },
  {
    id: "eg-3",
    name: "Quail Eggs (24)",
    category: "Eggs",
    price: 5.49,
    brand: "NatureFarm",
    rating: 4.5,
    inStock: false,
    image: "/images/eggs.jpg",
    priceRange: "Mid",
    tags: ["Specialty"],
  },

  // Clothing
  {
    id: "cl-1",
    name: "Ankara Print Dress",
    category: "Clothing",
    price: 29.99,
    brand: "AfriStyle",
    rating: 4.7,
    inStock: true,
    image: "/images/clothing.jpg",
    priceRange: "Mid",
    tags: ["Women", "African Print"],
  },
  {
    id: "cl-2",
    name: "Classic White Tee",
    category: "Clothing",
    price: 9.99,
    brand: "BasicWear",
    rating: 4.2,
    inStock: true,
    image: "/images/clothing.jpg",
    priceRange: "Low",
    tags: ["Unisex", "Casual"],
  },
  {
    id: "cl-3",
    name: "Agbada Set",
    category: "Clothing",
    price: 89.99,
    brand: "RegalWear",
    rating: 4.9,
    inStock: true,
    image: "/images/clothing.jpg",
    priceRange: "Sale",
    tags: ["Men", "African Print", "Formal"],
  },
  {
    id: "cl-4",
    name: "Linen Trousers",
    category: "Clothing",
    price: 24.99,
    brand: "UrbanBasics",
    rating: 4.3,
    inStock: false,
    image: "/images/clothing.jpg",
    priceRange: "Mid",
    tags: ["Men", "Casual"],
  },

  // Household Essentials
  {
    id: "hh-1",
    name: "Multi-Surface Cleaner",
    category: "Household Essentials",
    price: 3.49,
    brand: "CleanHome",
    rating: 4.4,
    inStock: true,
    image: "/images/household.jpg",
    priceRange: "Low",
    tags: ["Cleaning"],
  },
  {
    id: "hh-2",
    name: "Laundry Detergent 2L",
    category: "Household Essentials",
    price: 8.99,
    brand: "BrightWash",
    rating: 4.6,
    inStock: true,
    image: "/images/household.jpg",
    priceRange: "Mid",
    tags: ["Laundry"],
  },
  {
    id: "hh-3",
    name: "Toilet Paper (12 rolls)",
    category: "Household Essentials",
    price: 6.99,
    brand: "SoftTouch",
    rating: 4.5,
    inStock: true,
    image: "/images/household.jpg",
    priceRange: "Low",
    tags: ["Bathroom", "Bulk"],
  },
  {
    id: "hh-4",
    name: "Dish Soap Set",
    category: "Household Essentials",
    price: 5.49,
    brand: "CleanHome",
    rating: 4.3,
    inStock: false,
    image: "/images/household.jpg",
    priceRange: "Low",
    tags: ["Cleaning", "Kitchen"],
  },

  // Skincare
  {
    id: "sk-1",
    name: "Shea Butter Moisturizer",
    category: "Skincare",
    price: 14.99,
    brand: "GlowNaturals",
    rating: 4.8,
    inStock: true,
    image: "/images/skincare.jpg",
    priceRange: "Mid",
    tags: ["Moisturizer", "Natural"],
  },
  {
    id: "sk-2",
    name: "Vitamin C Serum",
    category: "Skincare",
    price: 24.99,
    brand: "LuxGlow",
    rating: 4.7,
    inStock: true,
    image: "/images/skincare.jpg",
    priceRange: "Sale",
    tags: ["Serum", "Anti-aging"],
  },
  {
    id: "sk-3",
    name: "Kojic Acid Soap",
    category: "Skincare",
    price: 7.99,
    brand: "ClearSkin",
    rating: 4.5,
    inStock: true,
    image: "/images/skincare.jpg",
    priceRange: "Low",
    tags: ["Cleanser", "Brightening"],
  },

  // Bodycare
  {
    id: "bc-1",
    name: "Cocoa Butter Lotion",
    category: "Bodycare",
    price: 9.99,
    brand: "BodyLux",
    rating: 4.6,
    inStock: true,
    image: "/images/bodycare.jpg",
    priceRange: "Low",
    tags: ["Moisturizer", "Natural"],
  },
  {
    id: "bc-2",
    name: "Exfoliating Body Scrub",
    category: "Bodycare",
    price: 12.99,
    brand: "ScrubCo",
    rating: 4.7,
    inStock: false,
    image: "/images/bodycare.jpg",
    priceRange: "Mid",
    tags: ["Exfoliator"],
  },
  {
    id: "bc-3",
    name: "Antibacterial Body Wash",
    category: "Bodycare",
    price: 6.99,
    brand: "CleanSkin",
    rating: 4.4,
    inStock: true,
    image: "/images/bodycare.jpg",
    priceRange: "Low",
    tags: ["Cleanser"],
  },

  // Haircare
  {
    id: "hc-1",
    name: "Jamaican Black Castor Oil",
    category: "Haircare",
    price: 11.99,
    brand: "NaturalRoots",
    rating: 4.9,
    inStock: true,
    image: "/images/haircare.jpg",
    priceRange: "Mid",
    tags: ["Oil", "Natural", "Growth"],
  },
  {
    id: "hc-2",
    name: "Deep Conditioning Mask",
    category: "Haircare",
    price: 14.99,
    brand: "HairGlow",
    rating: 4.7,
    inStock: true,
    image: "/images/haircare.jpg",
    priceRange: "Mid",
    tags: ["Treatment", "Moisture"],
  },
  {
    id: "hc-3",
    name: "Shampoo & Conditioner Set",
    category: "Haircare",
    price: 19.99,
    brand: "LuxHair",
    rating: 4.5,
    inStock: false,
    image: "/images/haircare.jpg",
    priceRange: "Mid",
    tags: ["Cleanser", "Moisture"],
  },

  // Snacks
  {
    id: "sn-1",
    name: "Plantain Chips",
    category: "Snacks",
    price: 2.99,
    brand: "CrunchAfrica",
    rating: 4.8,
    inStock: true,
    image: "/images/snacks.jpg",
    priceRange: "Low",
    tags: ["Savory", "African"],
  },
  {
    id: "sn-2",
    name: "Peanut Brittle",
    category: "Snacks",
    price: 3.49,
    brand: "SweetBite",
    rating: 4.6,
    inStock: true,
    image: "/images/snacks.jpg",
    priceRange: "Low",
    tags: ["Sweet"],
  },
  {
    id: "sn-3",
    name: "Chin Chin (Original)",
    category: "Snacks",
    price: 4.99,
    brand: "NaijaSnacks",
    rating: 4.9,
    inStock: true,
    image: "/images/snacks.jpg",
    priceRange: "Low",
    tags: ["Sweet", "African"],
  },
  {
    id: "sn-4",
    name: "Granola Bar Pack (6)",
    category: "Snacks",
    price: 6.99,
    brand: "HealthBite",
    rating: 4.3,
    inStock: false,
    image: "/images/snacks.jpg",
    priceRange: "Mid",
    tags: ["Healthy"],
  },

  // Kitchen Essentials
  {
    id: "ke-1",
    name: "Non-stick Frying Pan",
    category: "Kitchen Essentials",
    price: 24.99,
    brand: "ChefPro",
    rating: 4.6,
    inStock: true,
    image: "/images/kitchenessentials.jpg",
    priceRange: "Mid",
    tags: ["Cookware"],
  },
  {
    id: "ke-2",
    name: "Wooden Spoon Set",
    category: "Kitchen Essentials",
    price: 7.99,
    brand: "WoodCraft",
    rating: 4.4,
    inStock: true,
    image: "/images/kitchenessentials.jpg",
    priceRange: "Low",
    tags: ["Utensils", "Natural"],
  },
  {
    id: "ke-3",
    name: "Blender Pro 1000W",
    category: "Kitchen Essentials",
    price: 59.99,
    brand: "BlendMaster",
    rating: 4.8,
    inStock: true,
    image: "/images/kitchenessentials.jpg",
    priceRange: "Sale",
    tags: ["Appliances"],
  },
  {
    id: "ke-4",
    name: "Stainless Steel Pot Set",
    category: "Kitchen Essentials",
    price: 44.99,
    brand: "ChefPro",
    rating: 4.7,
    inStock: false,
    image: "/images/kitchenessentials.jpg",
    priceRange: "Sale",
    tags: ["Cookware"],
  },
];

export function getProductsByCategory(category: string): Product[] {
  return allProducts.filter(
    (p) => p.category.toLowerCase() === category.toLowerCase()
  );
}

export function getFilterOptionsForCategory(category: string) {
  const products = getProductsByCategory(category);
  const brands = [...new Set(products.map((p) => p.brand))];
  const tags = [...new Set(products.flatMap((p) => p.tags))];
  const priceRanges = [...new Set(products.map((p) => p.priceRange))];

  return { brands, tags, priceRanges };
}